#!/usr/bin/env python
"""build_library — generate LIBRARY.md + distribution/library.json, the brain's pull manifest.

A mechanical generator (like .claude/hooks/catalog.py — a plain script, NOT a hook and NOT a
skill). It scans the brain's CANONICAL shippable assets under example-project/.claude/
(skills/, agents/, commands/, workflows/), reads each asset's name/description live from its
frontmatter, merges the hand-authored distribution/registry.json overlay (category, portability,
dependency edges, companion hooks), and writes two artifacts:

    LIBRARY.md               (repo root) — human/agent index, grouped by category, with the
                             pull command for each asset and its transitive deps + companion hooks.
    distribution/library.json            — machine manifest that distribution/pull.py consumes.

Why example-project/.claude and not the repo-root .claude/: the repo-root .claude/ holds SYMLINKS
into example-project (the single-sourcing convention). example-project/.claude/ has the REAL files,
so it is the canonical library a consumer pulls from.

Usage:
    python distribution/build_library.py                 # build LIBRARY.md + library.json
    python distribution/build_library.py --check         # exit 1 if either artifact is stale
    python distribution/build_library.py --warn-if-stale # warn if stale, always exit 0

The frontmatter parser is duplicated from catalog.py on purpose (same convention catalog.py
itself follows: importing across bundles would couple them and break folder-level portability).
On macOS/Linux invoke with `python3`.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

LIBRARY_MARKER = "<!-- library: auto-generated by build_library.py — do not edit below -->"

HEADER = """# LIBRARY — pull capabilities from this brain

> The catalog of assets this brain ships to other projects, with each asset's dependencies and
> companion hooks. A Claude instance in another repo pulls from here. **Do not copy from the
> repo-root `.claude/`** — it is authoring-only and symlinked; the real, pullable files live in
> `example-project/.claude/`. Use the helper, which copies from the canonical tree and resolves
> dependencies + companion hooks automatically:
>
> ```
> python distribution/pull.py <asset-id> [<asset-id> ...] --dest <target-repo>/.claude
> ```
>
> See `distribution/README.md` for the full procedure. Generated by
> `python distribution/build_library.py` — do not edit below the marker.

## Reading order
> Pull commands list the requested asset; its `requires` and companion hooks are pulled
> automatically (transitively). `portable: no` marks stack/domain-specific assets only useful in a
> project with that stack.
"""

CATEGORY_ORDER = [
    ("operational", "Operational — session memory, knowledge routing, token economy, delegation"),
    ("objective-agent", "Objective agents — read-only design brains (defer the subjective how)"),
    ("presentation", "Branding → presentation pipeline (identity → design → format builders)"),
    ("python", "Python development family"),
    ("coding", "Cross-language coding baseline"),
    ("github", "GitHub workflow"),
    ("docs", "Documentation authoring"),
    ("planning", "Roadmap / version planning flow"),
    ("domain-quant", "Quantitative finance (domain-specific)"),
    ("domain-office", "Office add-ins: VSTO/.NET + VBA (domain-specific)"),
    ("infra", "Infrastructure helpers"),
    ("other", "Uncategorized (no registry entry — categorize in distribution/registry.json)"),
]

LAYERS = (
    ("skills", "skill"),
    ("agents", "agent"),
    ("commands", "command"),
    ("workflows", "workflow"),
)


def _force_utf8() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def brain_root() -> Path:
    """The repo root — the parent of this distribution/ directory."""
    return Path(__file__).resolve().parent.parent


def library_src() -> Path:
    """Canonical, real (non-symlinked) asset tree the brain ships from."""
    return brain_root() / "example-project" / ".claude"


def registry_path() -> Path:
    return brain_root() / "distribution" / "registry.json"


def library_json_path() -> Path:
    return brain_root() / "distribution" / "library.json"


def library_md_path() -> Path:
    return brain_root() / "LIBRARY.md"


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal YAML-frontmatter parse: scalar `key: value` and folded `key: >`/`|` blocks."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return {}
    fm = lines[1:end]
    data: dict[str, str] = {}
    i = 0
    while i < len(fm):
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", fm[i])
        if not m:
            i += 1
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in ("", ">", ">-", ">+", "|", "|-", "|+"):
            block, j = [], i + 1
            while j < len(fm) and (fm[j].startswith((" ", "\t")) or fm[j].strip() == ""):
                block.append(fm[j].strip())
                j += 1
            data[key] = " ".join(b for b in block if b)
            i = j
        else:
            data[key] = val.strip().strip("\"'")
            i += 1
    return data


def first_body_line(text: str) -> str:
    lines = text.splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
        if end is not None:
            start = end + 1
    for line in lines[start:]:
        s = line.strip().lstrip("#").strip()
        if s:
            return s
    return ""


def one_line(text: str, limit: int = 110) -> str:
    s = " ".join((text or "").split())
    if not s:
        return "(no description)"
    if len(s) <= limit:
        return s
    return s[:limit].rsplit(" ", 1)[0] + " …"


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def load_registry() -> dict:
    try:
        return json.loads(read(registry_path())).get("assets", {})
    except (ValueError, AttributeError):
        return {}


def discover_assets() -> dict[str, dict]:
    """Scan the canonical tree → {asset_id: {type, path, name, description}}. id is filesystem-based."""
    src = library_src()
    found: dict[str, dict] = {}

    skills_dir = src / "skills"
    if skills_dir.is_dir():
        for entry in sorted(skills_dir.iterdir()):
            skill_md = entry / "SKILL.md"
            if not skill_md.is_file():
                continue
            fm = parse_frontmatter(read(skill_md))
            found[f"skills/{entry.name}"] = {
                "type": "skill",
                "path": f"skills/{entry.name}",
                "name": fm.get("name") or entry.name,
                "description": one_line(fm.get("description", "")),
            }

    for subdir, typ in (("agents", "agent"), ("commands", "command"), ("workflows", "workflow")):
        base = src / subdir
        if not base.is_dir():
            continue
        for path in sorted(base.glob("*.md")):
            if path.name == "README.md":
                continue
            text = read(path)
            fm = parse_frontmatter(text)
            name = fm.get("name") or path.stem
            desc = fm.get("description") or first_body_line(text)
            found[f"{subdir}/{path.stem}"] = {
                "type": typ,
                "path": f"{subdir}/{path.name}",
                "name": name,
                "description": one_line(desc),
            }
    return found


def build_manifest() -> dict:
    """Merge discovered assets with the registry overlay into the machine manifest."""
    assets = discover_assets()
    overlay = load_registry()
    manifest_assets: dict[str, dict] = {}
    for aid, info in assets.items():
        ov = overlay.get(aid, {})
        manifest_assets[aid] = {
            **info,
            "category": ov.get("category", "other"),
            "portable": ov.get("portable", True),
            "requires": ov.get("requires", []),
            "hooks": ov.get("hooks", []),
        }
    return {
        "source": "example-project/.claude",
        "note": "Pull from the canonical tree above via distribution/pull.py — never from the "
                "symlinked repo-root .claude/. 'requires' and 'hooks' are pulled transitively.",
        "assets": manifest_assets,
    }


def render_library_json(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def render_library_md(manifest: dict) -> str:
    assets = manifest["assets"]
    by_cat: dict[str, list[str]] = {}
    for aid, info in assets.items():
        by_cat.setdefault(info["category"], []).append(aid)

    out: list[str] = []
    seen_cats = {c for c, _ in CATEGORY_ORDER}
    ordered = CATEGORY_ORDER + [(c, c) for c in sorted(by_cat) if c not in seen_cats]
    for cat, label in ordered:
        ids = sorted(by_cat.get(cat, []))
        if not ids:
            continue
        out.append(f"## {label}")
        out.append("")
        for aid in ids:
            info = assets[aid]
            portable = "" if info["portable"] else "  ·  _portable: no_"
            out.append(f"- **`{aid}`** — {info['description']}{portable}")
            extras = []
            if info["requires"]:
                extras.append("requires " + ", ".join(f"`{r}`" for r in info["requires"]))
            if info["hooks"]:
                extras.append("hooks " + ", ".join(f"`{h}`" for h in info["hooks"]))
            if extras:
                out.append(f"  - {' · '.join(extras)}")
            out.append(f"  - `python distribution/pull.py {aid} --dest <target>/.claude`")
        out.append("")

    preamble = HEADER
    if library_md_path().exists():
        existing = read(library_md_path())
        if LIBRARY_MARKER in existing:
            preamble = existing.split(LIBRARY_MARKER)[0]
    body = "\n".join(out).rstrip("\n") + "\n"
    return preamble.rstrip("\n") + "\n\n" + LIBRARY_MARKER + "\n\n" + body


def current(path: Path) -> str:
    return read(path) if path.exists() else ""


def missing_registry_entries(manifest: dict) -> list[str]:
    return sorted(aid for aid, info in manifest["assets"].items() if info["category"] == "other")


# --- modes -----------------------------------------------------------------

def mode_build() -> int:
    manifest = build_manifest()
    library_json_path().write_text(render_library_json(manifest), encoding="utf-8")
    library_md_path().write_text(render_library_md(manifest), encoding="utf-8")
    n = len(manifest["assets"])
    print(f"wrote LIBRARY.md + distribution/library.json ({n} assets)")
    missing = missing_registry_entries(manifest)
    if missing:
        print(f"note: {len(missing)} asset(s) lack a registry entry (category 'other'): "
              + ", ".join(missing))
    return 0


def mode_check() -> int:
    manifest = build_manifest()
    stale = (current(library_json_path()) != render_library_json(manifest)
             or current(library_md_path()) != render_library_md(manifest))
    if stale:
        print("stale: LIBRARY.md / distribution/library.json do not match the assets. "
              "Run `python distribution/build_library.py`.")
        return 1
    missing = missing_registry_entries(manifest)
    if missing:
        print(f"ok (manifest in sync), but {len(missing)} asset(s) lack a registry entry: "
              + ", ".join(missing))
    else:
        print("ok: LIBRARY.md + library.json are in sync with the assets")
    return 0


def mode_warn_if_stale() -> int:
    manifest = build_manifest()
    if (current(library_json_path()) != render_library_json(manifest)
            or current(library_md_path()) != render_library_md(manifest)):
        print("WARNING: LIBRARY.md / distribution/library.json are out of sync with the assets. "
              "Run `python distribution/build_library.py`.")
    return 0


def main(argv: list[str] | None = None) -> int:
    _force_utf8()
    parser = argparse.ArgumentParser(prog="build_library.py")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true",
                       help="verify the manifest matches the assets; exit 1 if stale")
    group.add_argument("--warn-if-stale", action="store_true",
                       help="print a warning if stale, always exit 0")
    args = parser.parse_args(argv)

    if args.check:
        return mode_check()
    if args.warn_if_stale:
        return mode_warn_if_stale()
    return mode_build()


if __name__ == "__main__":
    raise SystemExit(main())
